.TH "test_warp_client.c" 3 "Fri Jun 17 2022" "warpFDW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_warp_client.c
.SH SYNOPSIS
.br
.PP
\fC#include 'warp_client\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for warpFDW from the source code\&.
