.TH "test_req" 3 "Fri Jun 17 2022" "warpFDW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_req
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcomplete\fP"
.br
.ti -1c
.RI "size_t \fBbyteswritten\fP"
.br
.ti -1c
.RI "int \fBready\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Stream request context\&. Holds a value to indicate whether or not the request is completed\&. 
.SH "Field Documentation"
.PP 
.SS "size_t test_req::byteswritten"

.SS "int test_req::complete"

.SS "int test_req::ready"


.SH "Author"
.PP 
Generated automatically by Doxygen for warpFDW from the source code\&.
