.TH "test_warp_server.c" 3 "Fri Jun 17 2022" "warpFDW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_warp_server.c
.SH SYNOPSIS
.br
.PP
\fC#include 'warp_server\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBtestquerycb\fP (char *querystring)"
.br
.ti -1c
.RI "void \fBtestdatacb\fP (void **data, size_t *length)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.SS "void testdatacb (void ** data, size_t * length)"

.SS "int testquerycb (char * querystring)"

.SH "Author"
.PP 
Generated automatically by Doxygen for warpFDW from the source code\&.
